server:
  port: 8484

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://spring-db.cdkkyaw6cmyo.ap-northeast-2.rds.amazonaws.com:3306/spring
    username: root
    password: mariadb
  jpa:
    # SQL??? ?? ? ?? DBMS? ???? ??? ????
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl? ???? ??
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true   # SQL ??? ????? ??? ?? ??
    database: mysql  # DBMS ?? ??
  servlet:
    multipart:
      max-file-size: 3MB   # 한개의 파일의 최대 업로드 사이즈
      max-request-size: 20MB #1번 요청에 들어올 최대 업로드사이즈
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    com.study.todoapi: debug


jwt:
  secret: SJlE3ZwV0ognJAnF5c8AhfJikP54ml5M1xQZggQQR5YwgM+GW/ZbqvQMnBCI3IIrtO1CDJyxUphrntExyU99nA==

upload:
  path: D:/spring-prj/upload

#s3 setting
aws:
  credentials:
    accessKey:
    secretKey:
  region: ap-northeast-2
  bucketName: spring-todo-api-bucket-seon

